version: "3.8"
services:
  drone:
    image: drone/drone:latest
    ports:
      - "80:80"
    environment:
      - DRONE_SERVER_HOST=ownimage.ddns.net:80
      - DRONE_SERVER_PROTO=http
      - DRONE_SERVER_PROXY_PROTO=https
      - DRONE_RPC_SECRET=47f04d07742a7c1d6e269da408ecee15fbbd0846
      - DRONE_COOKIE_SECRET=e8206356c843d81e05ab6735e7ebf075
      - DRONE_COOKIE_TIMEOUT=720h
      - DRONE_GITHUB_CLIENT_ID=f3de1f2e786b2760f44c
      - DRONE_GITHUB_CLIENT_SECRET=47f04d07742a7c1d6e269da408ecee15fbbd0846
      - DRONE_LOGS_DEBUG=true
      - DRONE_CRON_DISABLED=true
    volumes:
      - ./data:/data
  runner:
    image: drone/drone-runner-docker:latest
    environment:
      - DRONE_RPC_HOST=drone
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_SECRET=47f04d07742a7c1d6e269da408ecee15fbbd0846
      - DRONE_TMATE_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

